---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/NYU/svm-r-markdown-templates-master/svm-latex-cv.tex
  html_document:
    df_print: paged
geometry: margin=1in
title: "CV"
author: "Annie Brandes-Aitken"
email: aba396@nyu.edu
# output:
#   html_document:
#     df_print: paged
#   pdf_document:
#     latex_engine: pdflatex
#     template: ~/Dropbox/NYU/svm-r-markdown-templates-master/svm-latex-cv.tex
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
jobtitle: NSF Graduate Research Fellow
keywords: R Markdown, academic CV, template
linkcolor: blue
fontawesome: yes
phone: 303 653 4404
address: Developmental Psychology. New York University
updated: no
urlcolor: blue
---
# Education

*Ph.D. in Developmental Psychology* \hfill 2022 (anticipated)  
New York University  
New York, NY


*B.S. in Psychology with Honors, Minor in Statistics* \hfill 2014  
California Polytechnic State University  
San Luis Obispo, CA



# Research Experience

*NSF Graduate Research Fellow*  
Neuroscience and Education Laboratory \hfill 2017-present  
New York University  
Advisors: Clancy Blair, PhD & Natalie Brito, PhD  

*Research Assistant*  
Education and Neuroscience Lab, Neuroscape Center \hfill 2015-2017  
University of California, San Francisco  
Advisors: Melina Uncapher, PhD & Adam Gazzaley PhD, MD  

*Research Coordinator*  
Sensory Neurodevelopment and Autism Program \hfill 2014-2017  
University of California, San Francisco  
Advisors: Elysa Marco, MD & Joaquin A. Anguera, PhD  


#Peer Reviewed Publications
Brito, N., Werchan, D., **Brandes-Aitken, A.N.**,Yoshikawa, H.,  Greaves, A., Zhang, M. Paid Maternal Leave is Associated with Infant Brain Function at 3-Months of Age. (2022). Developmental Psychology.

Braren, S., Perry, R., Ribner, A., **Brandes-Aitken, A.N.**, Brito, N., Blair, C.Prenatal Mother-Father Cortisol Co-regulation Predicts Infant Executive Functions at 24 Months (2021). Developmental Psychobiology.  

**Brandes-Aitken, A.N.**, Braren, S., Vogel, S., Perry, R., Brito, N., Blair, C. Within-Person Changes in Basal Cortisol and Caregiving Modulate Executive Attention across Infancy (2021). Development and Psychopathology.

Vogel, S., Perry,R., **Brandes-Aitken, A.N.**, Braren,S., Blair, C. Deprivation and threat as developmental mediators in the relation between early life socioeconomic status and executive functioning outcomes in early childhood (2021). Developmental Cognitive Neuroscience. 

Braren, S. **Brandes-Aitken, A.N.**, Perry,R., Williams,K., Lyons, K., Rowe‐Harriott, S., Blair, C., Baseline Hypothalamic–Pituitary–Adrenal Axis and Parasympathetic Nervous System Activity Interact to Predict Executive Functions in Low‐Income Children. (2021). Mind, Brain, and Educaiton.    

**Brandes-Aitken, A.N.**, Braren, S., Gandhi, J., Rowe-Harriott, S., Perry, R., Blair, C., Joint attention partially mediates the longitudinal relation between attuned caregiving and executive functions for low-income children (2020). Developmental Psychology.

Perry, R., Braren, S., Opendak, M., **Brandes-Aitken, A.N.**, Chopra, D., Sullivan, R., Blair, C. Elevated infant cortisol is necessary but not sufficient for transmission of environmental risk to infant social development: Cross-species evidence of mother–infant physiological social transmission. (2020). Development and Psychopathology.

Braren, S., **Brandes-Aitken, A.N.**, Ribner, A., Perry, R., Blair, C. Maternal Psychological Stress Moderates Diurnal Cortisol Linkage in Expectant Fathers and Mothers during Late Pregnancy (2019). Psychoneuroendocrinology.

Perry, R.,Braren, S., Rincon-Cortes, M.,  **Brandes-Aitken, A.N.**, Chopra, D., Sullivan, R., Blair, C. Enhancing Executive Functions through Social Interactions: Causal Evidence Using a Cross-Species Model. (2019). Frontiers in Psychology. 

Perry, R., Rincon-Cortes, M., Braren, S., **Brandes-Aitken, A.N.**, Opendak, M., Pollonini, G., Chopra, D., Raver, C.C., Alberini, C., Blair, C., Sullivan, R. 
Corticosterone administration targeting a hypo-reactive HPA axis rescues a socially avoidant phenotype in scarcity-adversity reared rats. (2019). Developmental Cognitive Neuroscience. 

**Brandes-Aitken, A.N.**, Braren, S., Swingler, M., Voegtline, K., Blair, C., Sustained Attention in Infancy: A Foundation for the Development of Self-Regulation in Children from Low-SES Backgrounds (2019). Journal of Experimental Child Psychology.

Payabvash, S., Palacios, E., Owen, J.P., Wang, M.B., Tavassoli, T., Gerdes, M.R., **Brandes Aitken, A.N.**,Marco, E. and Mukherjee, P. (2019).White Matter Connectome Correlates of Auditory Over-Responsivity: Edge Density Imaging and Machine-learning Classifiers. Frontiers in Integrative Neuroscience.  

Tavassoli, T., **Brandes-Aitken A. N.**, Chu, R., Porter, L., Schoen, S., 
Miller, L.J., Gerdes, M.R., Owen, J., Mukherjee, P., Marco, E.J. (2019).
Sensory over-responsivity: parent report, direct assessment measures, and neural architecture. Molecular Autism. 

Payabvash, S., Palacios, E., Owen, J.P., Wang, M.B., Tavassoli, T., Gerdes, M.R., **Brandes Aitken, A.**, Cuneo, D., Marco, E. and Mukherjee, P. (2019). White Matter Connectome Edge Density in Children with Autism Spectrum Disorders: Potential Imaging Biomarkers Using Machine Learning Models. Brain Connectivity. 

**Brandes-Aitken, A. N.**,  Anguera,J.A., Chang, Y.S., Demopoulos, C., Owen, J.P., Mukherjee, P., Gazzaley, A., Marco, E (2018). White Matter Microstructure Associations of Cognitive and Visuomotor Control in Children: A Sensory Processing Perspective. Frontiers in Integrative Neuroscience. 

Marco,  E.J., **Brandes-Aitken,A.N.**,  Prakas  Nair,  V.,  de  Gente,  G., Thomas,  S.,  Sherr,  E.H (2018). Prevalence of de novo neurodevelopment mutations and SNP enrichment in children with Sensory Processing Dysfunction (SPD): A prospective cohort study. BMC Medical Genomics. 

**Brandes-Aitken, A. N.**,  Anguera,J.A,. Rolle, C.E., Desai, S. S., Skinner, S.S., Gazzaley, A., Marco, E. (2018). Characterizing cognitive & visuomotor control in children with sensory processing dysfunction & autism. Neuropsychology. 32(2); 148-160.

*Anguera,J.A., \textbf{Brandes-Aitken, A. N.}* (*co-first authored*), Antovich, A. D. Rolle, C.E., Desai, S. S., Marco, E. J. (2017). A pilot study to determine the feasibility of enhancing cognitive abilities in children with sensory processing dysfunction. PLoS One. 12(4); 1-19. 

Demopoulos, C., Yu, N., Tripp, J., **Brandes-Aitken, A. N.**, Desai,  S. S., Hill,S. S., Antovich, A. D., Harris, J., Honma, S., Mizuiri, D., Nagarajan, S., Marco, E. J. (2017). Imaging Auditory and Somatosensory Cortical Responses in Children with Autism and Sensory Processing Dysfunction. Frontiers in human neuroscience. 11; 259.  
 
Anguera, J.A., **Brandes-Aitken, A. N.**, Rolle, C.E., Skinner, S.N., Desai, S.S., Bower, J,D., Martucci, E.W., Chung, W.K., Sherr, E.H., Marco, E.J. (2016). Characterizing cognitive control abilities in children with 16p11.2 deletion using adaptive "video game" technology: a pilot study. Translational Psychiatry. 6(9):e893.

Chang,Y.S., Gratiot,M., Owen,J.P., **Brandes-Aitken, A. N.**, Desai, S.S., Hill, S. S., Arnett, A.B.,  Harris, J., Marco, E.J., Mukherjee, P (2015). White matter microstructure is associated with auditory and tactile processing in children with and without sensory processing disorder. Frontiers in Neuroanatomy. 9:196.

Demopoulos, C., **Brandes-Aitken, A. N.**, Desai, S. S., Hill, S. S., Antovich, A. D., Harris, J., & Marco, E. J. (2015). Shared and Divergent Auditory and Tactile Processing in Children with Autism and Children with Sensory Processing Dysfunction Relative to Typically Developing Peers. Journal of the International Neuropsychological Society, 21(06), 444-454.

# Publications In Revision/Under Review

**Brandes-Aitken, A.N.**, Brito, N., Blair, C. Infant Attention Development through Social Interactions: Insights from developmental neuroscience
  
**Brandes-Aitken, A.N.**, Pino, N., Brito, N. Maternal Hair Cortisol Predicts Periodic and Aperiodic Infant Frontal EEG Activity Longitudinally Across Infancy

# Publications in Preperation

**Brandes-Aitken, A.N.**, Werchan, D., Brito, N. Neurophysiology of Sustained Attention in Early Infancy: Investigating Correlates with the Environment and Longitudinal Recognition Memory Outcomes


# Selected Published Abstracts	and	Conference Presentations:
**Brandes-Aitken, A.**, Braren, S., Greaves, A., Brito, N. (2021). Caregiver Hair Cortisol Predicts Differential Patterns of Longitudinal EEG Activity Across Infancy. Talk presented at the International Society for Developmental Psychobiology. Chicago, IL.

**Brandes-Aitken, A.**, Braren, S., Greaves, A., Brito, N. (2021). Parent cortisol and the neural underpinnings of attention and emotion regulation in infancy. Talk presented at the Society for Research in Child Development. Virtual Conference. 

**Brandes-Aitken, A.**, Braren, S., Greaves, A., Brito, N. (2020). Contributions of Cumulative Parent Cortisol to the Neural Underpinnings of Infant Attention and Emotion Regulation. Talk presented at the International Congress of Infant Studies. Virtual Conference. 

**Brandes-Aitken, A.**, Braren, S., Vogel, S., Perry, R., Blair, C. (2019). Linking Chronic Physiological Stress in Infancy to Sustained Attention in Toddlerhood and Working Memory in Early Childhood. International Society for Developmental Psychobiology. Chicago, IL.

**Brandes-Aitken, A.**, Braren, S., Greaves, A., Perry, R., Brito, N. (2019). Contributions of Cumulative Parent Cortisol, Language in the Home, and Socioeconomic Status to 3-Month Infant Resting EEG Power. FLUX Society. New York, New York. 

**Brandes-Aitken, A.**, Braren, S., Blair, C. (2019). Examining Longitudinal Associations of Socioeconomic Risk, Infant Attention and Early Childhood Self-Regulation. Talk presented at the Eastern Psychologial Association, New York, NY.  

**Brandes-Aitken, A.**, Braren, S., Blair, C. (2019). Influences of Poverty-Related Risk and Physiological Stress on Childhood Self-Regulation: Mediation through Infant Attention. Talk presented at the Society for Research in Child Development. Baltimore, MD.    

**Brandes-Aitken, A.**, Braren, S., Swingler, M., Voegtline, K., Blair, C. (2018). Attention in Infancy: A Foundation for the Development of Self-Regulation in Children from Low-SES Environments. International Society for Developmental Psychobiology. San Diego, CA.

**Brandes-Aitken, A.**, Braren, S., Blair, C. (2018). Detection of Novelty in Infants from Low-SES Backgrounds: A Functional Near-Infrared Spectroscopy Study. FLUX Society. Berlin, Germany. 

**Brandes-Aitken, A.**, Anguera, J., Owen, J., Mukherjee, P., Marco, E. (2017). Assessing Visuomotor Deficits in Children with SPD. International Meeting for Autism Research (IMFAR), San Francisco, CA.

**Brandes-Aitken, A.**, Anguera, J., Rolle, C., Antovich, A., Desai, S., Marco, E. (2016). Differentially Identifying and Remediating Attention Deficits in Children Affected by Sensory Processing Dysfunction. Society for Neuroscience. San Diego, CA.

**Brandes-Aitken, A.**, Skinner, S., Martucci, E., Bowers, J., Anguera, J. Gazzaley, A., Marco, E. (2016). Engaging and adaptive assessment for attention in 16p11.2 deletion carriers.  International  Meeting for Autism Research (IMFAR), Baltimore, MD.


#Invited Talks & Lectures

**Brandes-Aitken, A.**, Brito, N. (2020/2021). Introduction to EEG Methods in Research. Talk presented to neurology medical residents at New York University School of Medicine. New York, NY.

**Brandes-Aitken, A.**, Blair, C. (2019). Associations of Early Cognitive Control in Infancy. Talk presented at the Bezos Family Foundation Summit, Scottsdale, AZ.


#Honors, Awards & Fellowships
Dissertation Finishing Award  \hfill 2022 
 \textcolor{white}{white} New York University

Non-Academic Research Internship Supplemental Funding (awarded $20,000)  \hfill 2021  
 \textcolor{white}{white} National Science Foundation

Travel Award, International Society for Developmental Psychobiology \hfill 2021  
 \textcolor{white}{white} Chicago, IL 

Felix M. Warburg Memorial Steinhardt Scholarship \hfill 2021  
 \textcolor{white}{white} New York University

Travel Award, Society for Improving Psych. Science \hfill 2019  
 \textcolor{white}{white} Rotterdam, NL
 
Linda & Arthur Carter Steinhardt Scholarship \hfill 2019  
 \textcolor{white}{white} New York University

Travel Award, International Society for Developmental Psychobiology \hfill 2018  
 \textcolor{white}{white} San Diego, CA

Graduate Research Fellowship \hfill 2017-2020   
 \textcolor{white}{white} National Science Foundation  

Best Research Presentation Award  \hfill 2015  
 \textcolor{white}{white} Bay Area Autism Symposium
  
Research Travel Award  \hfill 2014  
 \textcolor{white}{white} Cal Poly  
  
Graduated Magna Cum Laude  \hfill 2014  
 \textcolor{white}{white} Cal Poly  
  

# Consulting Experience and Professional Services
Cortica  \hfill 2022-Present  
 \textcolor{white}{white} Research Scientist Consultant 

Brooklyn College\hfill 2021-Present  
 \textcolor{white}{white} Adjunct Lecturer

Social Creatures \hfill 2020-Present  
 \textcolor{white}{white} Community Impact Director 

Silicea Labs\hfill 2020  
 \textcolor{white}{white} Data Science Consultant 

UCSD Empathy Research Study\hfill 2020  
 \textcolor{white}{white} Statistician Consultant 


# Volunteer Outreach Experience

Quality Undergraduate Education and Scholarly Training (QUEST) program   \hfill 2019  
 \textcolor{white}{white} Mentor 

Brain Awareness Week Panel on Neuroscience and Policy  \hfill 2018  
 \textcolor{white}{white} Organizer and Co-Moderator    
  
Scientist Action and Advocacy Network  \hfill 2018-Present  
 \textcolor{white}{white} Member  
  
Girls Advancing in STEM   \hfill  2016-2017    
 \textcolor{white}{white} Mentor/Speaker  
 
Cal Poly NCAA Athletic & Academics Department  \hfill  2013-2014    
 \textcolor{white}{white} Statistics Tutor


#Ad Hoc Reviewing 
Developmental Science \hfill 2021  
Developmental Psychology \hfill 2020  
Developmental Science (co-reviewed with C.B.) \hfill 2018  
Psychiatry Research \hfill 2018  

#Trainings and Certifications
Functional Near-Infrared Spectroscopy (fNIRS) Training  \hfill 2017   
 \textcolor{white}{white} Martinos Institute for Biomedical Engineering at Harvard University  
  
Autism Diagnostic Observation Session Research Certified   \hfill 2015    
 \textcolor{white}{white} University of Washington   
  
MRI Training and Research Certified   \hfill 2014   
 \textcolor{white}{white} University of California, San Francisco  

  
<!-- # Programming & Software Experience -->
<!-- Python: -->

<!-- * PyGaze & PsychoPy: Experiment Programming for Eyetracking   -->

<!-- MatLab: -->

<!-- * EEGLAB: EEG processesing analysis   -->
<!-- * HOMER: fNIRS processing and analysis   -->

<!-- Brain Analyzer: -->

<!-- * EEG cleaning -->

<!-- R: -->

<!-- * Data Cleaning   -->
<!-- * Statistical Analysis & Graphics    -->

<!-- SAS: -->

<!-- * Statistical Analysis -->

<!-- Mplus:  -->

<!-- * Structural Equation Modeling -->



# References
Clancy Blair, PhD  
Professor of Psychology  
New York University  
Clancy.Blair@nyu.edu  

Natalie Brito, PhD  
Assistant Professor of Deveopmental Psychology   
New York University  
Natalie.Brito@nyu.edu    

Elysa Marco, MD  
Associate Professor of Neurology   
University of California, San Francisco  
elysa.marco@ucsf.edu  

Joaquin Anguera, PhD  
Assistant Professor of Neurology  
University of California, San Francisco  
joaquin.anguera@ucsf.edu  


